---
name: statsite
director_uuid: 93c01d2d-a2a5-49d8-8d02-389fd223a9cf 
compilation:
  workers: 2
  network: statsite
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 5
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

resource_pools:
  - name: small_z1
    network: statsite
    stemcell: default 

stemcells:
- alias: default
  name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  version: latest

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.1.0/24
    gateway: 10.244.1.0
    static: [10.244.1.34]

jobs:
  - name: statsite
    templates:
    - { release: statsite, name: statsite }
    instances: 1
    resource_pool: small_z1
    networks: [{name: default}]
    persistent_disk: 1024
    properties:
      vault:
        backend: 

releases:
- name: statsite-test-release
  version: latest
